server:
  port: 28852

spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account-service-db
    username: root
    password: qwerty123
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework: warn
  file:
    name: logs/spring-boot-logging.log

jwt:
  secret:
    access: eyJhbGciOiJIUzI1NiJ9ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0Vlnvt3d0vMHWZgdPyO4YiLCx6W5MtCqgIwDRvuak8